# Unfortunately, Makefiles, as good practice, should use tabs of width 8 - eugh
# Also, this comment is here as if it's inlnie with the recipe (as they're called) below,
# it gets sent to the shell (ie output)
test:
	emacs -Q --batch --eval "(setq user-emacs-directory default-directory)" -l init.el
